[package]
name = "nowasm"
version = "0.1.0"
edition = "2021"
categories = ["no-std"]

[dependencies]

[dev-dependencies]
orfail = "1.1.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
